# version.cmake
set(EMBEDDER_VERSION_MAJOR 1)
set(EMBEDDER_VERSION_MINOR 2)
set(EMBEDDER_VERSION_PATCH 2)
set(EMBEDDER_VERSION "${EMBEDDER_VERSION_MAJOR}.${EMBEDDER_VERSION_MINOR}.${EMBEDDER_VERSION_PATCH}")
