# version.cmake
set(EMBEDDER_VERSION_MAJOR 2)
set(EMBEDDER_VERSION_MINOR 0)
set(EMBEDDER_VERSION_PATCH 0)
set(EMBEDDER_VERSION "${EMBEDDER_VERSION_MAJOR}.${EMBEDDER_VERSION_MINOR}.${EMBEDDER_VERSION_PATCH}")
